package org.rebeam.sortable

import scala.collection.mutable

/**
  * A change in index of an item generated by dragging
  *
  * @param oldIndex The item's old index
  * @param newIndex The item's new index
  */
case class IndexChange(oldIndex: Int, newIndex: Int) {
  def updated[A](l: Seq[A]): Seq[A] = {
    val lb = mutable.Buffer(l: _*)
    val e = lb.remove(oldIndex)
    lb.insert(newIndex, e)
    lb
  }
}

